# Generated by Django 5.2.3 on 2025-07-13 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSpaceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('allocated_gb', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('active', 'Активно'), ('deleting', 'Удаляется'), ('deleted', 'Удалено'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Экземпляр дискового пространства',
                'verbose_name_plural': 'Экземпляры дискового пространства',
                'ordering': ['created_at'],
            },
        ),
    ]
