# Generated by Django 5.2.3 on 2025-07-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskspaceinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('active', 'Активно'), ('deleting', 'Удаляется'), ('deleted', 'Удалено'), ('error', 'Ошибка'), ('deletion_error', 'Ошибка удаления')], default='pending', max_length=20),
        ),
    ]
