# Generated by Django 5.2.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VmInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ram_gb', models.IntegerField()),
                ('vcpu', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('external_id', models.CharField(blank=True, help_text='ID VM во внешней системе (например, AWS Instance ID)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Виртуальная машина',
                'verbose_name_plural': 'Виртуальные машины',
            },
        ),
    ]
