# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminstance',
            name='ansible_stderr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vminstance',
            name='ansible_stdout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
