# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm_service_app', '0002_vminstance_ansible_stderr_vminstance_ansible_stdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminstance',
            name='disk_gb',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='vminstance',
            name='os_type',
            field=models.CharField(choices=[('ubuntu', 'Ubuntu Server'), ('centos', 'CentOS Stream'), ('debian', 'Debian')], default='ubuntu', max_length=50),
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vminstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('provisioning', 'В процессе подготовки'), ('active', 'Активна'), ('error', 'Ошибка'), ('deleted', 'Удалена')], default='pending', max_length=20),
        ),
    ]
